apiVersion: apps/v1 
kind: Deployment
metadata:
  name: tripviewer-dep
spec:
  selector:
    matchLabels:
      app: tripviewer
  replicas: 1
  template:
    metadata:
      labels:
        app: tripviewer
    spec:
      containers:
      - name: tripviewer
        image: [edithere]/tripviewer:1.0
        ports:
        - containerPort: 80
        env:
        - name: TRIPS_API_ENDPOINT
          value: "http://10.0.50.154"
        - name: USERPROFILE_API_ENDPOINT
          value: "http://10.0.137.22"          
          
          





